ZSHHOME="${HOME}/.zsh.d"

# homebrew
export PATH="$PATH:/opt/homebrew/bin"

source $ZSHHOME/common.zsh
source $ZSHHOME/environments.zsh
source $ZSHHOME/alias.zsh
source $ZSHHOME/functions.zsh
source $ZSHHOME/zplug.zsh

prompt pure
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
