# ターミナルの表示設定
export PS1='\[\033[32m\]\u@\h\[\033[35m\]:\[\033[35m\]\W\[\033[31m\]\[\033[00m\]\n\$ '

# alias
alias ll="ls -la"
alias gg="git grep -H --heading --break"
alias gd="git diff"
alias gf="git fetch"
alias gb="git branch"
alias gs="git status"
alias gl="git log"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
