[settings]
experimental = true
disable_backends = ["asdf"]

[env]
_.path = ["~/.cargo/bin"]

[tools]
aws = "latest"
terraform = "latest"
github-cli = "latest"
ghq = "latest"
node = "latest"
python = "latest"
go = "latest"
rust = "latest"
uv = "latest"
"cargo:ripgrep" = "latest"
"cargo:bat" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:zoxide" = "latest"
