[[snippets]]
  description = "ping"
  command = "ping 8.8.8.8"
  tag = ["network", "google"]
  output = ""

[[snippets]]
  description = "calcurator"
  command = "bc -ql"
  tag = ["general"]
  output = ""

[[snippets]]
  description = "gnu debugger"
  command = "gdb -q "
  tag = ["gnu", "c"]
  output = ""

[[snippets]]
  description = "postgres client"
  command = "psql -h localhost -p 5432 -U postgres"
  tag = ["db", "postgres"]
  output = ""

[[snippets]]
  description = "python venv create"
  command = "python3 -m venv .venv"
  tag = ["python"]
  output = ""

[[snippets]]
  description = "python venv activate"
  command = ". ./.venv/bin/activate"
  tag = ["python"]
  output = ""

[[snippets]]
  description = "open docs except dependencies"
  command = "cargo doc --open --no-deps"
  tag = ["rust"]
  output = ""

[[snippet]]
  description = "run onetime container"
  command = "docker run -it --rm -p 80:80 -v `pwd`:/work image_name /bin/bash"
  tag = ["docker"]
  output = ""
