[[snippets]]
  description = "ping"
  command = "ping 8.8.8.8"
  tag = ["network", "google"]
  output = ""

[[snippets]]
  description = "calcurator"
  command = "bc -ql"
  tag = ["general"]
  output = ""

[[snippets]]
  description = "gnu debugger"
  command = "gdb -q "
  tag = ["gnu", "c"]
  output = ""
