[[snippets]]
  description = "ping"
  command = "ping 8.8.8.8"
  tag = ["network", "google"]
  output = ""

[[snippets]]
  description = "calcurator"
  command = "bc -ql"
  tag = ["general"]
  output = ""

[[snippets]]
  description = "gnu debugger"
  command = "gdb -q "
  tag = ["gnu", "c"]
  output = ""

[[snippets]]
  description = "postgres client"
  command = "psql -h localhost -p 5432 -U postgres"
  tag = ["db", "postgres"]
  output = ""

[[snippets]]
  description = "python venv create"
  command = "python3 -m venv .venv"
  tag = ["python"]
  output = ""

[[snippets]]
  description = "python venv activate"
  command = ". ./.venv/bin/activate"
  tag = ["python"]
  output = ""

[[snippets]]
  description = "open docs except dependencies"
  command = "cargo doc --open --no-deps"
  tag = ["rust"]
  output = ""

[[snippets]]
  description = "execute integration test"
  command = "cargo test --test integration_test"
  tag = ["rust", "cargo", "test"]
  output = ""

[[snippets]]
  description = "curl POST"
  command = "curl -vX POST -H \"Content-Type: application/json\" -d '{}'"
  output = ""

[[snippets]]
  description = "aws ecs command"
  command = "aws ecs execute-command --cluster <cluster-name> --task <task-no> --container <container-name> --interactive --command 'bin/sh'"
  output = ""
